### PR TITLE
Fix #16: issue with removing folders

### LINKED ISSUE #16: Error in outputs when removing folders
If you remove a folder from the list, it seems to introduce an error. I suspect this is because the resource still exists but the output is being interpolated.

Sample code: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/org/folders.tf#L17

Error:
```
Error: Error in function call

  on .terraform/modules/folders-root/terraform-google-modules-terraform-google-folders-0c75f1c/outputs.tf line 19, in output "names_and_display_names":
  19:   value       = zipmap(var.names, google_folder.folders.*.display_name)
    |----------------
    | google_folder.folders is tuple with 2 elements
    | var.names is list of string with 1 element

Call to function "zipmap" failed: number of keys (1) does not match number of
values (2).
```

Likely fix is simply to only grab the first n google_folder resources for the zipmap.

### PR DESCRIPTION
**Pull request by morgante**
Fixes #16 by slicing the outputs to the length of inputs.

### CODE REVIEW

**Comment by ludoo** [comment]
This is a fix, but there's a potential corner case. State has

```names = ["one", "two", "three"]```

and then change to

```names = ["one", "three"]```

and run `terraform output`. The outputs will be incorrect imho. I would prefer an error that forces removing outputs until state matches vars. What do you think?

**Comment by ludoo** [comment]
@averbuks read my comment above...

**Comment by morgante** [comment]
> The outputs will be incorrect imho. 

Are you sure?

Only until/unless you run `terraform apply`. I don't think there should be any expectation that a Terraform config with un-applied changes produces reasonable results.

In fact, it would be the same outcome even without this. This is truncating the list, but the out

> and run terraform output. The outputs will be incorrect imho. I would prefer an error that forces removing outputs until state matches vars. What do you think?

We should not force people to edit module internals simply to apply a perfectly valid config.

**Comment by ludoo** [comment]
I misinterpred the order of execution, so disregard my previous comments! Thanks @morgante for pointing that out privately :)

**Comment by ludoo** [comment]
I mulled this over a bit as there are similar issues insme the service accounts module, and there's something I can't wrap my head around.

Removing an element from the `names` variable triggers output errors in zipmaps as the resource length in state does not match names length, and this I get of course (and slicing fixes it).

What I don't get is why a similar error isn't raised when an element is **added** to the `names` variable. The outputs length should still be mismatched vs name length, and slicing it should of course make no difference, but I don't seem to be able to reproduce this case.

Can someone who understands Terraform internals shed some light here? Is the evaluation only done when destroying resources, which resonates with the issues open in the Terraform repository on this subject, that mostly seem to deal with `destroy` operations?

**Comment by aaron-lane** [comment]
@ludoo what is the output in the scenario of adding an extra name?

**Comment by ludoo** [comment]
> @ludoo what is the output in the scenario of adding an extra name?

What you'd expect after a successful apply. The issue is only when deleting a resource, either through a change in inputs or when destroying, so Morgante's patch addresses it.

**Pull request merged**
